# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-30 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profie_image',
            new_name='profile_image',
        ),
    ]
