# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profiledetailscomp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetailscomp',
            name='user',
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='short_bio',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='profiledetailscomp',
        ),
    ]
