# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-15 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='post_count',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
