# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171221_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_profile', to='api.profiledetails'),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_profile', to='api.profiledetails'),
        ),
        migrations.DeleteModel(
            name='followers',
        ),
    ]
