# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 12:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20171221_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='followfollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_profile', to='api.followfollowing')),
                ('following', models.ManyToManyField(blank=True, related_name='following_profile', to='api.followfollowing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='following',
        ),
    ]
