# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171221_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='followfollowing',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
