# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_followfollowing_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followfollowing',
            name='number',
        ),
    ]
