# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-24 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_followfollowing_user_name_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followfollowing',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='followfollowing',
            name='following',
        ),
        migrations.RemoveField(
            model_name='followfollowing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profie_post',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='post_count',
        ),
        migrations.DeleteModel(
            name='followfollowing',
        ),
    ]
