# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-24 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171224_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_profile', to='api.profiledetails'),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_profile', to='api.profiledetails'),
        ),
    ]
