# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171224_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='username_follow',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
