# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180104_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='username_follow',
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='follow_id',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
