# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_bac'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bac',
            name='bac_level',
            field=models.FloatField(null=True),
        ),
    ]
